### ISSUE TITLE
Wither shoots too fast when near

### ISSUE THREAD

**Issue by EnderGirl1500** [Insane96/ProgressiveBosses#134]
I don't know if this is intended or a bug, but the people on my server couldn't beat the first level of the wither. Is the first level more difficult than the vanilla's one?

**Versions:**
 - Minecraft: 1.18.2
 - Fabric: 0.14.8
 - Progressive Bosses: 1.0.6

**Expected behavior**
The wither should be (in my opinion) as difficult as the vanilla one or even easier.

**Comment by Insane96** [comment]
This isn't the Fabric version repository. Also the first level isn't supposed to be much harder than vanilla

**Comment by EnderGirl1500** [comment]
I couldn't find the Fabric version. Where can I report the bug? Coz in minecraft vanilla in difficult mode you can kill the wither with 4 golems, but one of the players tried it with 6 golems (normal mode) and the wither destroyed them in seconds!

**Comment by Insane96** [comment]
Try the curseforge page.

Also yes, just checked and the first Wither is slightly harder due to shooting faster, the skulls are harder to dodge and when the target is near and breaking more blocks around him thus making him unreachable melee after a few hits
![2022-07-02_07 47 52](https://user-images.githubusercontent.com/7185104/176988333-70a951f5-17f4-4721-aad7-488386e3d46c.png)

**Comment by Insane96** [comment]
~~Thanks, by investigating I've actually found a bug that makes the Wither shoot faster than he should when near.~~

Nope, that was intended
