### ISSUE TITLE
Add configurable explosion power of skulls

### ISSUE THREAD

**Issue by Insane96** [Insane96/ProgressiveBosses#138]

**Comment by 48004800** [comment]
> _No description provided._

Would you consider adding the modification option of "wither" status effect level

**Comment by 48004800** [comment]
> > _No description provided._
> 
> Would you consider adding the modification option of "wither" status effect level

Due to the injury immune mechanism of minecraft, a large number of attacks by BOSS (especially wither) are ineffective and the effect of wither state higher than 3 cannot fully play a role.

**Comment by Insane96** [comment]
Immunity frames do not prevent damage, it just prevents damage lower than the previous taken, so if you take 1 heart of damage and 5 ticks later you take 5 hearts of damage, you'll take 4 more hearts of damage, so the damage is not wasted.
Immunity frames are there for a reason, to prevent getting obliterated in a few split seconds.

**Comment by 48004800** [comment]
> Immunity frames do not prevent damage, it just prevents damage lower than the previous taken, so if you take 1 heart of damage and 5 ticks later you take 5 hearts of damage, you'll take 4 more hearts of damage, so the damage is not wasted. Immunity frames are there for a reason, to prevent getting obliterated in a few split seconds.


The mod I installed cancels the damage immunity time of projectiles
The wither becomes more powerful. I have installed  Mod with powerful equipment, so even then I can still beat wither

To get to the point, I don't want to cancel the injury immunity time.There's no need to do this
Ender dragon has  powerful fireball attack that can cause magic damage
And its damage is configurable
But the magic damage of within only has the effect of "wither" state
It is currently not configurable
I mean, even if the effect level of the wither state can be configured, because of the damage immunity, the damage of the wither state will reach the maximum at the third level. After that, even if the level is increased, there will be no change.
Just make the "wither" effect an exception（Now players cannot modify the level of the wither state effect imposed by the wither, so it is meaningless）




<img width="641" alt="image" src="https://user-images.githubusercontent.com/78255094/205927530-4e420c3f-ad0d-40ed-b5b8-a03d71fc15a1.png">

**Comment by Insane96** [comment]
I'll probably add a way to change wither effect power, for people that want the constant damage sound in the ears lol, but disabled by default. Also you'll be able to change the effect power to level I, since with IguanaTweaks Reborn you can disable protection and Wither effect becomes quite strong (you're dead in 20 seconds really lol).

**Comment by 48004800** [comment]
I think it would be better if the effect level of the wither state was increased, causing more damage each time, rather than increasing the frequency of damaging entities.    But the wither state effect of minecraft is not designed in this way
The effect of the state wither III is also acceptable. Wither III will cause two hazards within one second.
The effect of this state is stronger than that of Poisoning II.

Finally, let's mention the theme of this issue
What do you think of modifying the explosive power of  the wither skull?
This issue has existed for several months

**Comment by Insane96** [comment]
> What do you think of modifying the explosive power of the wither skull?

I don't think I will change it in anyway by default since there's already the bonus damage that kicks in, only make it configurable.

**Comment by Insane96** [comment]
This is now available in v4
